// <auto-generated />
using System;
using CandidateHub.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandidateHub.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250301051715_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CandidateHub.Domain.Entities.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BestCallTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BestCallTime = new DateTime(2025, 3, 2, 5, 17, 12, 320, DateTimeKind.Utc).AddTicks(7493),
                            Comment = "I am open to Work",
                            Email = "hasanboevs@icloud.com",
                            FirstName = "Muhammadyusuf",
                            GitHubProfile = "https://github.com/hasanboevs1",
                            LastName = "Hasanboyev",
                            LinkedInProfile = "https://uz.linkedin.com/in/hasanboevs",
                            PhoneNumber = "+998975949511"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
